name: misc_utilities
description: Collection of shared utility functions
version: 0.2.2
homepage: https://github.com/savannahghi/misc_utilities
repository: https://github.com/savannahghi/misc_utilities
issue_tracker: https://github.com/savannahghi/misc_utilities/issues
documentation: https://github.com/savannahghi/misc_utilities/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  app_wrapper:  ^0.2.0
  async_redux: ^16.0.0
  domain_objects: ^0.2.2
  dotted_border: ^2.0.0+2
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.24
  flutter_image_compress: ^1.1.2
  flutter_svg: ^1.1.5
  http: ^0.13.5
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6996
  path_provider: ^2.0.11
  platform: ^3.1.0
  rxdart: ^0.27.5
  shared_themes: ^0.2.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
