name: sil_misc
description: Collection of small utility funcations
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  countdown_flutter: ^0.1.2
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_spinkit: ^3.1.0
  firebase_performance: ^0.3.2
  rxdart: ^0.24.0
  rflutter_alert: ^1.0.3
  path_provider: ^1.6.8
  country_pickers: ^1.3.0
  pin_code_text_field: ^1.7.1
  http: ^0.12.0+4
  camera: ^0.5.8+17
  file_picker: ^2.1.4
  flutter_svg: ^0.19.1
  dotted_border: ^1.0.5
  camera_camera: ^1.0.34+1
  flutter_image_compress: ^0.7.0
  material_design_icons_flutter: 4.0.5045
  sil_themes:
   git:
     url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
     ref: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  assets:
    - assets/
