name: sil_misc
description: Collection of small utility functions
publish_to: 'none'
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  countdown_flutter: ^0.1.2
  flutter:
    sdk: flutter
  camera: ^0.8.0
  camera_camera: ^2.0.0-nullsafety.2
  country_pickers: ^1.3.0
  dotted_border: ^2.0.0-nullsafety.0
  http: ^0.13.0
  firebase_performance: ^0.6.0
  file_picker: ^3.0.0
  flutter_image_compress: ^1.0.0-nullsafety
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  pin_code_text_field: ^1.8.0
  rxdart: ^0.26.0
  rflutter_alert: ^2.0.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  sil_themes:
    git: 
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
      ref: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.0
  

flutter:
  assets:
    - assets/
